### ISSUE TITLE
Vigilante phase-2 mainnet readiness

### ISSUE THREAD

**Issue by SebastianElvis** [babylonchain/vigilante#225]
This page contains all tasks that need to be done in vigilante before the final testnet / mainnet.

## Code quality / maintainability

- [ ] **(HIGH PRIORITY)** bitcoin: replace existing BTC subscribers with btcclient/notifier.go (#199 )
- [ ] **(HIGH PRIORITY)** chore: unify interfaces for services/goroutines (#198 )
- [ ] **(HIGH PRIORITY)** Submitter: refactoring points (#178 )
- [ ] **(HIGH PRIORITY)** chore: universal parameters for all packages (#70 )

## Security

- [ ] **(HIGH PRIORITY)** BTC staking tracker: potential OOM with many BTC delegations (#223 )
- [ ] BTC staking tracker: ensure FP is not slashed before slashing (#224 )

- [ ] **(HIGH PRIORITY)** Timestamping monitor: Need alert when submitting checkpoints with inappropriate epochs (#177 )
- [ ] Timestamping monitor: Persists the last processed height and epoch (#219 )
- [ ] Timestamping monitor: Add persistent storage to save checking states (#156 )
- [ ] Timestamping monitor: "monitor" Segmentation Violation (#193 )

- [ ] **(HIGH PRIORITY)** Submitter: Use EstimateSmartFee RPC call to estimate tx fee after btcd upgrade to v0.23 (#117 )
- [ ] Submitter: consider dust when choosing UTXOs (#41 )
- [ ] Submitter: avoid resending if part of checkpoint has been sent (#67 )

## Performance

- [ ] **(HIGH PRIORITY)** Timestamping monitor: Reduce PRC calls in btc controller (#218 )
- [ ] **(HIGH PRIORITY)** bitcoin: use semaphore / thread pool to prevent spamming Bitcoin node (#196 )
- [ ] **(HIGH PRIORITY)** BTC staking tracker: only maintaining active and unbonding BTC delegations (#197 )
